@extends('template')

@section('title', 'homepage')

@section('body')
    <article class="content">
        <section class="pull-left">
            <div class="container">
                <div class="ssd col-xs-12">
                    <br>
                    <h2 class="set-left"><span class="htb6">What instrument should my child learn?</span></h2>
                    <h4 class="set-left"><span class="htb3">Before reading this, please read our note on <a href="/learn">Why you should learn to play an instrument or to sing</a> </span></h4>
                    <p>
                        OK – so you (or your child) wants (or you want them) to learn to play a musical instrument – that’s great!
                    </p>
                    <p>
                        First of all, let’s say “It’s never too late to start!” Adults can learn too, it isn’t that difficult, it’s not rocket science and it will bring you hours of joy and pleasure for the  rest of your life. However, this site is primarily concerned with providing help and encouragement for youngsters – so let’s start at the beginning...
                    </p>

                    <h4 class="set-left"><span class="htb1">Age 0-3(/4)</span></h4>
                    <p>
                        <span class="bold_div">Sing!</span> Sing to your child, sing around the house, sing nursery songs with them, get them singing at parent &amp; toddler groups, or get them singing at parties, make sure your child gets to sing at school, or at church, or joins a youth choir of some kind. They don’t need to have formal singing lessons – just try to get them singing! The sooner they start the better. Try to make sure that, along the way, they are at least introduced to the idea of reading music, even if it is just the simplest, basic things like realising that notes go up and down and recognising that the spacing of written notes relates to the rhythm of the music!
                    </p>
                    <h4 class="set-left"><span class="htb2">Age 3-6</span></h4>
                    <p>
                        Most musical instruments are not designed for and cannot really be played by very young children. The one instrument that all children can learn to play from a very young age is the <span class="bold_div">Piano</span> (or electronic keyboard). Learning the piano is also the best way to learn to read music so, even if the child doesn’t make great progress or want to carry on with piano later, everything they have learnt will help them enormously when they start to play anything else. If they give up the piano at any point, it’s easy to go back to it later in life and just carry on where they left off.
                    </p>
                    <h4 class="set-left"><span class="htb3">Age 4 or 5 onwards </span></h4>
                    <p>
                        <span class="bold_div">Strings!</span> It really is best to start on string instruments as early as possible. (Specifically, the <span class="bold_div">Violin</span> or <span class="bold_div">Cello</span>. The basics are all the same and, if they want, they can easily move on to <span class="bold_div">Viola</span> or <span class="bold_div">Double Bass</span> later, when they are bigger.)
                    </p>
                    <p>
                        Violins and Cellos come in all different sizes, right down to ones that suit the smallest children. It is easy to change up to a bigger instrument as they grow. The other two great things about learning to play string instruments is that (a) there is a shortage of string players so there will always be plenty of opportunities to play with others in a wide range of different types of orchestras and ensembles, playing a wide range of types of music – and (b) most of the greatest music ever written, by most of the greatest composers who ever lived, involves string players. So, if you can persuade or encourage your child to learn Violin or Cello, please do – it is the best possible choice! (And remember – it is never too late to start!)
                    </p>
                    <h4 class="set-left"><span class="htb4">Age 6 or 7 onwards </span></h4>
                    <p>
                        <span class="bold_div">Recorder!</span> If your child hasn’t yet started to learn an instrument, or has decided they want a change from piano or from strings, then there are plenty of other instruments they could learn – but most of them will still be too big to handle. The next best thing to do is to introduce them to the Recorder. These also come in different sizes – and the skills they learn from playing recorder are easily transferable to all the other wind instruments. Not only that, they will be able to play in groups with other recorder players, learning about playing together – and they will continue to develop their reading and other musical skills.
                    </p>
                    <h4 class="set-left"><span class="htb5">Age 8 onwards </span></h4>
                    <p>
                        <span class="bold_div">Almost everything else!</span> Depending on how big your child has grown by this age (and, to a certain extent, how mature they are) it starts to become possible for them to begin to learn most of the other instruments.
                    </p>
                    <h4 class="set-left"><span class="htb6">The Instruments </span></h4>
                    <p>Let’s start with the <span class="bold_div">Woodwind</span> (Flute, Oboe, Clarinet, Bassoon &amp; Saxophone). Of these, the Flute, Clarinet and Saxophone are certainly the easiest to learn and the cheapest to buy! Because of that, far more kids learn them and, because of that, there is more competition and thus fewer opportunities to play them in orchestras, ensembles, bands etc. in the future.</p>
                    <p>The <span class="bold_div">Flute</span> is fine if your child’s mouth is the right sort of shape and they have no problems making a good sound by blowing across a hole. If not, try something else. If your child does take to the Flute, it is worth remembering that, later on, they might also want to learn the <span class="bold_div">Piccolo</span> (a kind of baby Flute). This is worth doing, they are not expensive and being able to play one opens up more opportunities. Nobody plays or learns just the Piccolo, it is always played by Flute players (Flautists).</p>
                    <p>Most people can easily make a sound on the <span class="bold_div">Clarinet</span> and it’s a good choice if your child likes it. Progress is pretty easy at first. Don’t be tempted by cheap, plastic, beginner type instruments, especially smaller ones pitched in C. When your child’s hands are big enough, start on a normal Clarinet (pitched in B flat). After a few years, when your child has reached about grade 5 standard or above, you will need to buy an additional clarinet, (pitched in A) or to sell your original and buy a matching pair. All good Clarinettists play both – they have to. Most music is written for either one or the other and they sometimes have to change mid-piece. (It is possible to take grade 8 and to play in wind and jazz bands with only a B flat instrument – but why limit your child’s future to that and not enable them to enjoy playing all the vast amount of other, great orchestral and chamber music that needs both?)</p>
                    <p>Lots of kids want to learn the <span class="bold_div">Saxophone</span> – it’s often seen as “cool” and, maybe, as a faintly rebellious instrument to play. Please try to persuade them to learn the Clarinet first and take up the Sax later! The Saxophone is rather limited in the types of music that it can play (jazz and wind bands) and, more importantly, if you can play the Clarinet, the skills are immediately and very quickly transferable to Saxophone – but it doesn’t work the other way round. Why play just one, limited instrument when you can just as easily play two and have the best of all worlds?</p>
                    <p>Best of all, learn the <span class="bold_div">Oboe</span> or <span class="bold_div">Bassoon!</span> These are slightly more difficult to begin with, they are a little bit more expensive and the child’s hands need to be slightly bigger – but they are “shortage” instruments. Players are in great demand and thus opportunities for joining orchestras and ensembles are far more plentiful. Lots of children have probably never even heard an Oboe or a Bassoon – give them a chance. Let them have a go! If they find they can cope with the mouth shape required to make a good noise using a double reed, then please do all you can to encourage them to persist. The longer term advantages are enormous.</p>

                    <p>Now, on to the <span class="bold_div">Brass</span> instruments (Trumpet, Cornet, Horn, Trombone, Euphonium Tuba and various others.) Basically, all brass instruments work on the same principle – making the sound by buzzing your lips through a metal mouthpiece – and so the skills are easily and fairly quickly transferable from one to the other. </p>
                    <p>The <span class="bold_div">Trumpet</span> and the <span class="bold_div">Cornet</span> are virtually identical and most good players play both. The Cornet is slightly easier to handle so it’s not a bad idea for youngsters to start on the Cornet – but the Trumpet offers far more opportunities for playing a wider range of music in various types of orchestras, jazz bands etc., whereas the Cornet is mostly used in Brass Bands. Most brass players of all instruments start on cornet or trumpet and switch to the other instruments when they get older or bigger (or wiser).</p>
                    <p>The <span class="bold_div">Horn</span> (we don’t call it the French Horn any more) used to have a reputation as the most difficult instrument to play but that isn’t really true nowadays. It is a glorious instrument, offering the widest possible range of musical opportunities – and there is a big shortage of players, so it is an excellent choice. It is possible to get small horns for little players but, if your child is too small to handle a full-size instrument, it’s just as easy to start on Trumpet or Cornet and switch later. The Horn mouthpiece is slightly bigger than that for Trumpet and Cornet.</p>
                    <p>The <span class="bold_div">Trombone</span> is slightly different from the other brass instruments because it has a slide instead of valves. That does make it rather difficult for small children to handle. However, the slide positions equate to the valve combinations on all the other brass instruments so it isn’t rocket science to switch from Trumpet or Cornet. The mouthpiece is slightly bigger again. It’s a fun instrument, offering plenty of scope.</p>
                    <p>The <span class="bold_div">Tuba</span> is too big for most youngsters, but the <span class="bold_div">Euphonium</span> is a smaller and lighter option to start with. Most players play both. If your child likes making a big, fat, fruity noise then this is the instrument for them. Again, good players are in short supply.</p>
                    <p>All the other brass instruments (Flugel Horn, Tenor Horn, Baritone etc.) are pretty well only used in Brass Bands. Nothing wrong with that, brass bands are quite popular in this part of the country and it can be great fun playing in them. However, it does seem a pity to limit the opportunities available to your child by choosing one of these as a starter instrument. If you can play any of the main brass instruments above, you can quite easily pick up and learn a brass band instrument at any time – but it doesn’t work so easily the other way round so it’s better to keep options open.</p>
                    <p>Just two more points about brass instruments:- <br> (1) If you learn to play the Horn, Trumpet or Cornet then, whilst learning to read music, it is also very important to learn to transpose. (A teacher will explain that if you don’t understand). If you learn right from the start, it isn’t difficult at all. <br> (2) If you learn Trombone, Euphonium or Tuba, do please learn bass clef notation. (Trombonists will also need to learn tenor and alto clef notation later.) If you learn treble clef notation, you will only be able to play in brass bands – pretty well everyone else uses bass clef. (Again, a teacher will explain if needed.)</p>

                    <p><span class="bold_div">Percussion:</span> It isn’t surprising that lots of children want to learn to play the drums! They are so prominent in much of the pop music that gets foisted upon them all the time – and, of course, it looks like (and is) great fun to make a lot of noise and bash things around! However, there is far more to percussion playing than just Drum Kit. </p>
                    <p>The first important technique to learn is <span class="bold_div">Side Drum</span> (Snare Drum) and this can be done just using sticks on a practise pad, so it doesn’t make much noise. The skills learnt apply to all sorts of other drums too. </p>
                    <p>The next most important skill is to learn how to play the <span class="bold_div">Timpani</span> (Kettle Drums). These are big drums, so you will need access to them at a school or music centre. The drums are tuned to a specific not and most modern ones have foot pedals so that you can change the notes quickly and easily. Start with just 2 timpani, then 3 and eventually 4 or even 5. These are the instruments that are most used in orchestras, bands and almost every large group of instrumentalists. Good players are in short supply so opportunities will be plentiful.</p>
                    <p>The other group of percussion instruments that are essential to learn are what we call <span class="bold_div">Tuned Percussion</span>. This includes Xylophone, Marimba, Vibraphone &amp; Glockenspiel – and, when you can play one, you can pretty well play them all. These are the instruments on which you can really “make music” and, again, good players are in short supply.</p>
                    <p>After (or alongside) these, there are loads of other instruments that you need to learn to use: Cymbals, Triangle, Tambourine, Bass Drum, Tubular Bells, Castanets, Rattles, Whistles and a great many more that you will never have heard of! </p>
                    <p>Of course, in order to play any of these in any orchestra or band, you will need to learn to read music – so please don’t limit yourself to just playing Drum Kit!</p>

                    <p><span class="bold_div">Guitar</span>: Again, the Guitar is a very popular choice, for obvious reasons – and the reason it is so ubiquitous in “popular” music is really because that sort of guitar playing is so easy! Almost anyone with a reasonable talent for and understanding of music can pick up a guitar and teach themselves to play most pop, rock and folk music pretty quickly. If your child is really sold on the idea of playing the guitar, then get them a normal, acoustic guitar and try to make sure they are taught to (a) play properly – in other words, they learn what we call “classical” guitar techniques – and (b) that they learn to read music. That way, they will have the best of all worlds and,if they do end up just wanting to play pop music, they will be streets ahead of the game! Smaller children might start on the Ukulele until their hands are big enough.</p>
                    <p><span class="bold_div">Harp</span>: Unless you live in Wales, there are very few people who learn to play the Harp, which is a great pity because it is such a beautiful instrument. It’s certainly worth giving it serious consideration.</p>

                </div>
            </div>
        </section>
    </article>

@endsection
